# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a58bea6f52877381ff8a3adb4fb3bf67f16ab66699976dad2155bc5781b9fb476372f4321f50d4566cde48ae0da2ce089691bc754a8a6be765f1bf3beff8001d

test:
  secret_key_base: 3fd4a7c9edca9b3b5030a6c418bb7d72c2001be7a0d22f2615172c9ee6a0994976ab51595378b3f2e42e907f40307e72baf46551361c03118a0f2ff36e744152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
